/* 
 * API for Pet Project
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using Newtonsoft.Json;

namespace PetApiClient
{
    public class ClinicHistoryRM
    {
        public int PetId { get; set; }
        public int? VetId { get; set; }
        public int? ClinicId { get; set; }
        public string Anamnesis { get; set; }
        public string Treatment { get; set; }
        public string Diagnostic { get; set; }
        public string ClinicalSign { get; set; }
        public string Observations { get; set; }
        public DateTime ArrivalDate { get; set; }
        public DateTime DischargeDate { get; set; }
    }
}
