/* 
 * API for Pet Project
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace PetApiClient
{
    /// <summary>
    /// Vaccination
    /// </summary>
    [DataContract]
    public partial class Vaccination :  IEquatable<Vaccination>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Vaccination" /> class.
        /// </summary>
        /// <param name="IdVaccination">IdVaccination.</param>
        /// <param name="IdPet">IdPet.</param>
        /// <param name="Name">Name.</param>
        /// <param name="LaboratoryName">LaboratoryName.</param>
        /// <param name="VaccinationDate">VaccinationDate.</param>
        public Vaccination(int? IdVaccination = default(int?), int? IdPet = default(int?), string Name = default(string), string LaboratoryName = default(string), DateTime? VaccinationDate = default(DateTime?))
        {
            this.IdVaccination = IdVaccination;
            this.IdPet = IdPet;
            this.Name = Name;
            this.LaboratoryName = LaboratoryName;
            this.VaccinationDate = VaccinationDate;
        }
        
        /// <summary>
        /// Gets or Sets IdVaccination
        /// </summary>
        [DataMember(Name="idVaccination", EmitDefaultValue=false)]
        public int? IdVaccination { get; set; }
        /// <summary>
        /// Gets or Sets IdPet
        /// </summary>
        [DataMember(Name="idPet", EmitDefaultValue=false)]
        public int? IdPet { get; set; }
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Gets or Sets LaboratoryName
        /// </summary>
        [DataMember(Name="laboratoryName", EmitDefaultValue=false)]
        public string LaboratoryName { get; set; }
        /// <summary>
        /// Gets or Sets VaccinationDate
        /// </summary>
        [DataMember(Name="vaccinationDate", EmitDefaultValue=false)]
        public DateTime? VaccinationDate { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Vaccination {\n");
            sb.Append("  IdVaccination: ").Append(IdVaccination).Append("\n");
            sb.Append("  IdPet: ").Append(IdPet).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  LaboratoryName: ").Append(LaboratoryName).Append("\n");
            sb.Append("  VaccinationDate: ").Append(VaccinationDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Vaccination);
        }

        /// <summary>
        /// Returns true if Vaccination instances are equal
        /// </summary>
        /// <param name="other">Instance of Vaccination to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Vaccination other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.IdVaccination == other.IdVaccination ||
                    this.IdVaccination != null &&
                    this.IdVaccination.Equals(other.IdVaccination)
                ) && 
                (
                    this.IdPet == other.IdPet ||
                    this.IdPet != null &&
                    this.IdPet.Equals(other.IdPet)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.LaboratoryName == other.LaboratoryName ||
                    this.LaboratoryName != null &&
                    this.LaboratoryName.Equals(other.LaboratoryName)
                ) && 
                (
                    this.VaccinationDate == other.VaccinationDate ||
                    this.VaccinationDate != null &&
                    this.VaccinationDate.Equals(other.VaccinationDate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.IdVaccination != null)
                    hash = hash * 59 + this.IdVaccination.GetHashCode();
                if (this.IdPet != null)
                    hash = hash * 59 + this.IdPet.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.LaboratoryName != null)
                    hash = hash * 59 + this.LaboratoryName.GetHashCode();
                if (this.VaccinationDate != null)
                    hash = hash * 59 + this.VaccinationDate.GetHashCode();
                return hash;
            }
        }

    }

}
