//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetApiClient {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Uris {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Uris() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetApiClient.Uris", typeof(Uris).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://petprojectapi.azurewebsites.net/api/.
        /// </summary>
        public static string BaseApiUrl {
            get {
                return ResourceManager.GetString("BaseApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://petprojectapi.azurewebsites.net.
        /// </summary>
        public static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appointments.
        /// </summary>
        public static string UriAppointments {
            get {
                return ResourceManager.GetString("UriAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to owners.
        /// </summary>
        public static string UriOwners {
            get {
                return ResourceManager.GetString("UriOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pets.
        /// </summary>
        public static string UriPets {
            get {
                return ResourceManager.GetString("UriPets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users.
        /// </summary>
        public static string UriUsers {
            get {
                return ResourceManager.GetString("UriUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vets.
        /// </summary>
        public static string UriVets {
            get {
                return ResourceManager.GetString("UriVets", resourceCulture);
            }
        }
    }
}
